//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Testers = new HashSet<Tester>();
            this.Sectors = new HashSet<Sector>();
            this.Shifts = new HashSet<Shift>();
        }
    
        public int MemberID { get; set; }
        public string Name { get; set; }
        public string SesaID { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
    
        public virtual ICollection<Tester> Testers { get; set; }
        public virtual ICollection<Sector> Sectors { get; set; }
        public virtual ICollection<Shift> Shifts { get; set; }
    }
}
