//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductModel
    {
        public ProductModel()
        {
            this.TestUnits = new HashSet<TestUnit>();
        }
    
        public int ProductModelID { get; set; }
        public string Name { get; set; }
        public string Rating { get; set; }
        public Nullable<int> CycleTime { get; set; }
        public int FamilyID { get; set; }
    
        public virtual Family Family { get; set; }
        public virtual ICollection<TestUnit> TestUnits { get; set; }
    }
}
