//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTransaction
    {
        public int TestTransactionID { get; set; }
        public string EngineerID { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Timestamp { get; set; }
        public Nullable<int> Status { get; set; }
        public int UnitTestCycleID { get; set; }
        public int BayID { get; set; }
    
        public virtual Bay Bay { get; set; }
        public virtual UnitTestCycle UnitTestCycle { get; set; }
    }
}
