//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BSDSContext : DbContext
    {
        public BSDSContext()
            : base("name=BSDSContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BayBreakdown> BayBreakdowns { get; set; }
        public DbSet<Bay> Bays { get; set; }
        public DbSet<Family> Families { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<ProductModel> ProductModels { get; set; }
        public DbSet<Sector> Sectors { get; set; }
        public DbSet<Shift> Shifts { get; set; }
        public DbSet<StatusInfo> StatusInfoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TesterBreakdown> TesterBreakdowns { get; set; }
        public DbSet<Tester> Testers { get; set; }
        public DbSet<TestTransaction> TestTransactions { get; set; }
        public DbSet<TestUnit> TestUnits { get; set; }
        public DbSet<UnitTestCycle> UnitTestCycles { get; set; }
    }
}
