//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sector
    {
        public Sector()
        {
            this.Testers = new HashSet<Tester>();
            this.Members = new HashSet<Member>();
        }
    
        public int SectorID { get; set; }
        public string Name { get; set; }
        public int LocationID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Tester> Testers { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
