//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesterApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tester
    {
        public Tester()
        {
            this.Bays = new HashSet<Bay>();
            this.TesterBreakdowns = new HashSet<TesterBreakdown>();
            this.Members = new HashSet<Member>();
        }
    
        public int TesterID { get; set; }
        public string Name { get; set; }
        public int Status { get; set; }
        public int SectorID { get; set; }
    
        public virtual ICollection<Bay> Bays { get; set; }
        public virtual Sector Sector { get; set; }
        public virtual ICollection<TesterBreakdown> TesterBreakdowns { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}
